language: ruby
rvm:
- 2.5.1
script:
- "./script/index_gems.sh 0 5"
env:
  matrix:
    - STARTING_POINT=0
    - STARTING_POINT=50
    - STARTING_POINT=100
    - STARTING_POINT=150
    - STARTING_POINT=200
    - STARTING_POINT=250
    - STARTING_POINT=300
    - STARTING_POINT=350
    - STARTING_POINT=400
    - STARTING_POINT=450
    - STARTING_POINT=500
    - STARTING_POINT=550
    - STARTING_POINT=600
    - STARTING_POINT=650
    - STARTING_POINT=700
    - STARTING_POINT=750
    - STARTING_POINT=800
    - STARTING_POINT=850
    - STARTING_POINT=900
    - STARTING_POINT=950
  global:
    secure: nhP4q3fvMtoZgUXShIRdQvsW4Q2xJ14xpqFaysiWMvAwgZ3xxuUwFPkt1GbCUJxKWkm6KUBKlYNvxHN0M1EAF2ixNxbQ2H9ZULRdBy5tUGw8SOeFPCQ42Jmle9iomdIrIiqmKZgZxYc9MAADc/zfJf8eFF8/3AMdoffx2T7E614Ach3rnsnpjETKZDpO/Br3SrPfXCzagoH+hy26Ltg7swQ9BxqUWygbnWCFzHhVt/JgO64LjmeO3O9RJBGXI3ZZwEuJ/snpo23Cw19EDtbV074wqHPaM51GS8YyfJ9L/XhBMySDtwFYh33oeOUS2rIF+gRK2epaPR5qClFbMDlgxbZPpElNr0Ztx/4/qTR1OUtt/+OVCe4BSU7BO1xI6Qu5DzvKIwJ97VWqvEElWGk9mjuParh5V6cQxeAtFRz/k2KDu0P+eSRw5zpnPZ6p4eJqcVgi9yNTveWMJ6qnqz15+V6MzGO6dtcbldSv96Y+q77NqayCcp9cfFg/BXaJDbD3n0E/knSoESb4O0yCW8QjFq9BsoXtn7zEgClzVTW0zHj+BOvTcy3Bb61Jt/e+cCRrWb0tTAa/5paeWWoCuGZOAZRYMQQrzwNGHGLSRz8fEiSpYN1uQiQJUbNIK/ISZMgwVKr4KkU0fDkOp/KP6r+eb/oGX6me8nCPNqkdFpeFyf0=
